package com.dev.idea.plugins.tomcat.ui.server.sections;

import com.dev.idea.plugins.tomcat.conf.TomcatRunConfiguration;
import com.dev.idea.plugins.tomcat.TomcatConstants;
import com.intellij.icons.AllIcons;
import com.intellij.ide.browsers.WebBrowser;
import com.intellij.ide.browsers.WebBrowserManager;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.ShowSettingsUtil;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.ui.TitledSeparator;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBTextField;
import com.intellij.util.ui.JBUI;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class BrowserLaunchSection implements ConfigurationSection {

    private static final Logger LOG = Logger.getInstance(BrowserLaunchSection.class);
    private static final String URL_PREFIX = "http://" + TomcatConstants.DEFAULT_HOST + ":";

    private final Project project;
    private JBCheckBox afterLaunchCheckBox;
    private ComboBox<String> browserComboBox;
    private JButton browserConfigButton;
    private JBCheckBox withJavaScriptDebuggerCheckBox;
    private JBTextField urlField;
    private JPanel panel;

    private boolean isInitialized = false;
    /** Tracks whether the URL was set by auto-generation (true) or edited by the user (false). */
    private boolean urlIsAutoGenerated = false;
    /** Guard to distinguish programmatic setText() from user typing. */
    private boolean isSettingUrl = false;

    public BrowserLaunchSection(Project project) {
        this.project = project;
    }

    @Override
    @NotNull
    public JPanel createPanel() {
        if (panel == null) {
            initializeComponents();
            createLayout();
            isInitialized = true;
            loadConfiguration();
        }
        return panel;
    }

    private void initializeComponents() {
        afterLaunchCheckBox = new JBCheckBox("After launch");
        browserComboBox = new ComboBox<>();
        browserComboBox.setRenderer(new BrowserComboRenderer());
        browserConfigButton = new JButton("...");
        withJavaScriptDebuggerCheckBox = new JBCheckBox("with JavaScript debugger");
        urlField = new JBTextField();

        // Detect when the user manually types in the URL field — mark as user-owned
        urlField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override public void insertUpdate(javax.swing.event.DocumentEvent e) { onUserEdit(); }
            @Override public void removeUpdate(javax.swing.event.DocumentEvent e) { onUserEdit(); }
            @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { onUserEdit(); }
            private void onUserEdit() {
                if (isInitialized && !isSettingUrl) {
                    urlIsAutoGenerated = false;
                }
            }
        });

        browserConfigButton.setPreferredSize(new Dimension(JBUI.scale(30), JBUI.scale(25)));

        afterLaunchCheckBox.addActionListener(e -> updateBrowserControls());
        browserConfigButton.addActionListener(e -> configureBrowsers());
    }

    private void createLayout() {
        panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBorder(JBUI.Borders.empty(0));

        TitledSeparator separator = new TitledSeparator("Open browser");
        separator.setMaximumSize(new Dimension(Integer.MAX_VALUE, separator.getPreferredSize().height));
        panel.add(separator);

        JPanel formPanel = new JPanel(ConfigurationSection.createAlignedGridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = JBUI.insets(2, 0, 2, 6);
        gbc.gridwidth = 1;

        gbc.gridx = 0; gbc.gridy = 0;
        formPanel.add(afterLaunchCheckBox, gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        formPanel.add(browserComboBox, gbc);

        gbc.gridx = 2;
        gbc.weightx = 0;
        gbc.fill = GridBagConstraints.NONE;
        formPanel.add(browserConfigButton, gbc);

        gbc.gridx = 3;
        gbc.weightx = 0;
        formPanel.add(withJavaScriptDebuggerCheckBox, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        gbc.insets = JBUI.insets(2, 0, 2, 6);
        formPanel.add(new JBLabel("URL:"), gbc);

        gbc.gridx = 1; gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.insets = JBUI.insets(2, 4, 2, 8);
        formPanel.add(urlField, gbc);

        formPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, formPanel.getPreferredSize().height));
        panel.add(formPanel);
    }

    @Override
    public void loadConfiguration() {
        if (!isInitialized || browserComboBox == null) {
            return;
        }

        try {
            String previousSelection = (String) browserComboBox.getSelectedItem();

            browserComboBox.removeAllItems();
            browserComboBox.addItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);

            // Use IntelliJ's built-in WebBrowserManager to get active configured browsers
            for (WebBrowser browser : WebBrowserManager.getInstance().getActiveBrowsers()) {
                browserComboBox.addItem(browser.getName());
            }

            // Restore previous selection if still available
            if (previousSelection != null) {
                browserComboBox.setSelectedItem(previousSelection);
                if (browserComboBox.getSelectedItem() == null || !previousSelection.equals(browserComboBox.getSelectedItem())) {
                    browserComboBox.setSelectedIndex(0);
                }
            }

            updateBrowserControls();

        } catch (Exception e) {
            LOG.error("Error loading browsers", e);
            if (browserComboBox.getItemCount() == 0) {
                browserComboBox.addItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);
            }
        }
    }

    @Override
    public void resetFrom(@NotNull TomcatRunConfiguration configuration) {
        if (!isInitialized) {
            return;
        }

        try {
            afterLaunchCheckBox.setSelected(configuration.isAfterLaunchEnabled());
            withJavaScriptDebuggerCheckBox.setSelected(configuration.isWithJsDebugger());

            // Use saved URL if available, otherwise generate from port/context
            isSettingUrl = true;
            String savedUrl = configuration.getBrowserUrl();
            if (savedUrl != null && !savedUrl.isEmpty()) {
                urlField.setText(savedUrl);
                // A persisted URL that matches the auto-generated pattern is still auto-managed;
                // a custom URL (different host, extra path segments, etc.) is user-owned.
                urlIsAutoGenerated = savedUrl.startsWith(URL_PREFIX);
            } else {
                String contextPath = configuration.getContextPath();
                Integer port = configuration.getHttpPort();
                if (contextPath != null && port != null) {
                    urlField.setText(URL_PREFIX + port + contextPath);
                } else if (port != null) {
                    urlField.setText(URL_PREFIX + port + TomcatConstants.DEFAULT_CONTEXT_PATH);
                } else {
                    urlField.setText(URL_PREFIX + TomcatConstants.DEFAULT_PORT + TomcatConstants.DEFAULT_CONTEXT_PATH);
                }
                urlIsAutoGenerated = true;
            }
            isSettingUrl = false;

            // Restore saved browser selection
            String savedBrowser = configuration.getBrowserName();
            if (savedBrowser != null && !savedBrowser.isEmpty()) {
                browserComboBox.setSelectedItem(savedBrowser);
            } else {
                browserComboBox.setSelectedItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);
            }

            updateBrowserControls();

        } catch (Exception e) {
            LOG.error("Error resetting browser configuration", e);
        }
    }

    @Override
    public void applyTo(@NotNull TomcatRunConfiguration configuration) throws ConfigurationException {
        try {
            if (isInitialized && afterLaunchCheckBox != null) {
                configuration.setAfterLaunchEnabled(afterLaunchCheckBox.isSelected());

                if (urlField != null) {
                    configuration.setBrowserUrl(urlField.getText().trim());
                }

                if (browserComboBox != null && browserComboBox.getSelectedItem() != null) {
                    configuration.setBrowserName(browserComboBox.getSelectedItem().toString());
                }

                if (withJavaScriptDebuggerCheckBox != null) {
                    configuration.setWithJsDebugger(withJavaScriptDebuggerCheckBox.isSelected());
                }
            }
        } catch (Exception e) {
            throw new ConfigurationException("Failed to apply browser configuration: " + e.getMessage());
        }
    }

    @Override
    public boolean isConfigurationValid() {
        return true;
    }

    @Override
    public boolean isModified(@NotNull TomcatRunConfiguration config) {
        if (!isInitialized) {
            return false;
        }

        try {
            if (!Objects.equals(afterLaunchCheckBox.isSelected(), config.isAfterLaunchEnabled())) {
                return true;
            }

            String configUrl = config.getBrowserUrl();
            String currentUrl = urlField != null ? urlField.getText().trim() : "";
            if (!Objects.equals(currentUrl, configUrl != null ? configUrl : "")) {
                return true;
            }

            String configBrowser = config.getBrowserName();
            String currentBrowser = getSelectedBrowser();
            if (!Objects.equals(currentBrowser, configBrowser != null ? configBrowser : TomcatConstants.BROWSER_SYSTEM_DEFAULT)) {
                return true;
            }

            if (withJavaScriptDebuggerCheckBox != null &&
                    withJavaScriptDebuggerCheckBox.isSelected() != config.isWithJsDebugger()) {
                return true;
            }

        } catch (Exception e) {
            LOG.warn("Error checking browser configuration modifications", e);
        }

        return false;
    }

    @Override
    @NotNull
    public List<ValidationInfo> validateSettings() {
        return Collections.emptyList();
    }

    private void updateBrowserControls() {
        if (!isInitialized) {
            return;
        }

        try {
            boolean enabled = afterLaunchCheckBox.isSelected();

            browserComboBox.setEnabled(enabled);
            browserConfigButton.setEnabled(enabled);
            withJavaScriptDebuggerCheckBox.setEnabled(enabled);
            urlField.setEnabled(enabled);
        } catch (Exception e) {
            LOG.error("Error updating browser controls", e);
        }
    }

    private void configureBrowsers() {
        // Open IntelliJ's built-in "Web Browsers and Preview" settings page
        ShowSettingsUtil.getInstance().showSettingsDialog(project, "Web Browsers and Preview");
        // Reload browser list after settings dialog closes (user may have changed browsers)
        loadConfiguration();
    }

    public boolean isAfterLaunchEnabled() {
        return isInitialized && afterLaunchCheckBox != null && afterLaunchCheckBox.isSelected();
    }

    public String getUrl() {
        return isInitialized && urlField != null ? urlField.getText().trim() : "";
    }

    public String getSelectedBrowser() {
        if (isInitialized && browserComboBox != null && browserComboBox.getSelectedItem() != null) {
            return browserComboBox.getSelectedItem().toString();
        }
        return TomcatConstants.BROWSER_SYSTEM_DEFAULT;
    }

    public boolean isJavaScriptDebuggerEnabled() {
        return isInitialized && withJavaScriptDebuggerCheckBox != null &&
                withJavaScriptDebuggerCheckBox.isSelected();
    }

    /**
     * Updates the context path portion of the browser URL when deployments change.
     * Only modifies the URL if it was auto-generated — never overwrites a
     * user-customized URL. This is the user's choice to keep.
     */
    public void updateUrlContext(String contextPath) {
        if (!isInitialized || urlField == null || contextPath == null) return;

        // Respect user's custom URL — only update auto-generated ones
        if (!urlIsAutoGenerated) return;

        String currentUrl = urlField.getText();
        if (currentUrl.startsWith(URL_PREFIX)) {
            int portStart = URL_PREFIX.length();
            int pathStart = currentUrl.indexOf('/', portStart);
            String portPart = (pathStart != -1) ? currentUrl.substring(0, pathStart) : currentUrl;
            isSettingUrl = true;
            urlField.setText(portPart + contextPath);
            isSettingUrl = false;
        }
    }

    private static class BrowserComboRenderer extends com.intellij.ui.SimpleListCellRenderer<String> {
        @Override
        public void customize(@NotNull JList<? extends String> list, String value, int index,
                              boolean selected, boolean hasFocus) {
            if (value != null) {
                setText(value);
                Icon icon = findBrowserIcon(value);
                setIcon(icon != null ? icon : AllIcons.General.Web);
            }
        }

        private Icon findBrowserIcon(String browserName) {
            if (TomcatConstants.BROWSER_SYSTEM_DEFAULT.equalsIgnoreCase(browserName)
                    || "Default".equalsIgnoreCase(browserName)) {
                return AllIcons.General.Web;
            }
            for (WebBrowser browser : WebBrowserManager.getInstance().getBrowsers()) {
                if (browserName.equals(browser.getName())) {
                    return browser.getIcon();
                }
            }
            return null;
        }
    }
}
