package com.dev.idea.plugins.tomcat.ui.server.sections;

import com.dev.idea.plugins.tomcat.conf.TomcatRunConfiguration;
import com.dev.idea.plugins.tomcat.TomcatConstants;
import com.intellij.icons.AllIcons;
import com.intellij.ide.browsers.WebBrowser;
import com.intellij.ide.browsers.WebBrowserManager;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.openapi.options.ShowSettingsUtil;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.ComboBox;
import com.intellij.openapi.ui.ValidationInfo;
import com.intellij.ui.TitledSeparator;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBTextField;
import com.intellij.ui.components.panels.VerticalLayout;
import com.intellij.util.ui.JBUI;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.*;
import java.awt.event.ActionListener;
import java.net.URI;
import java.util.Collections;
import java.util.List;
import java.util.Objects;

public class BrowserLaunchSection implements ConfigurationSection {

    private static final Logger LOG = Logger.getInstance(BrowserLaunchSection.class);
    private static final String URL_PREFIX = "http://" + TomcatConstants.DEFAULT_HOST + ":";

    private final Project project;
    private JBCheckBox afterLaunchCheckBox;
    private ComboBox<String> browserComboBox;
    private JButton browserConfigButton;
    private JBCheckBox withJavaScriptDebuggerCheckBox;
    private JBTextField urlField;
    private JPanel panel;

    private boolean isInitialized = false;
    /** Tracks whether the URL was set by auto-generation (true) or edited by the user (false). */
    private boolean urlIsAutoGenerated = false;
    /** Guard to distinguish programmatic setText() from user typing. */
    private boolean isSettingUrl = false;
    /** Guard to distinguish programmatic combo changes from user selection. */
    private boolean isSettingBrowser = false;
    /** The browser name the user explicitly chose — null means auto/default. */
    private String userSelectedBrowser = null;
    private DocumentListener urlDocListener;
    private ActionListener browserActionListener;

    public BrowserLaunchSection(Project project) {
        this.project = project;
    }

    @Override
    @NotNull
    public JPanel createPanel() {
        if (panel == null) {
            initializeComponents();
            createLayout();
            isInitialized = true;
            loadConfiguration();
        }
        return panel;
    }

    private void initializeComponents() {
        afterLaunchCheckBox = new JBCheckBox("After launch");
        browserComboBox = new ComboBox<>();
        browserComboBox.setRenderer(new BrowserComboRenderer());
        browserConfigButton = new JButton("...");
        // "with JavaScript debugger" is plugin-gated. Match the IntelliJ Platform
        // convention of hiding plugin-gated controls rather than showing a disabled
        // upsell — if the JavaScript/TypeScript plugin is not installed the checkbox
        // never appears in the layout.
        if (isJavaScriptPluginAvailable()) {
            withJavaScriptDebuggerCheckBox = new JBCheckBox("with JavaScript debugger");
        }
        urlField = new JBTextField();

        // Detect when the user manually types in the URL field — mark as user-owned
        urlDocListener = new DocumentListener() {
            @Override public void insertUpdate(DocumentEvent e) { onUserEdit(); }
            @Override public void removeUpdate(DocumentEvent e) { onUserEdit(); }
            @Override public void changedUpdate(DocumentEvent e) { onUserEdit(); }
            private void onUserEdit() {
                if (isInitialized && !isSettingUrl) {
                    urlIsAutoGenerated = false;
                }
            }
        };
        urlField.getDocument().addDocumentListener(urlDocListener);

        // Detect when the user manually picks a browser — mark as user-owned
        browserActionListener = e -> {
            if (isInitialized && !isSettingBrowser) {
                String selected = (String) browserComboBox.getSelectedItem();
                if (selected != null) {
                    userSelectedBrowser = selected;
                }
            }
        };
        browserComboBox.addActionListener(browserActionListener);

        afterLaunchCheckBox.addActionListener(e -> updateBrowserControls());
        browserConfigButton.addActionListener(e -> configureBrowsers());
    }

    private void createLayout() {
        panel = new JPanel(new VerticalLayout(0));
        panel.setBorder(JBUI.Borders.empty(0));

        panel.add(new TitledSeparator("Open browser"));

        JPanel formPanel = new JPanel(ConfigurationSection.createAlignedGridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = JBUI.insets(2, 0, 2, 6);
        gbc.gridwidth = 1;

        gbc.gridx = 0; gbc.gridy = 0;
        formPanel.add(afterLaunchCheckBox, gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        formPanel.add(browserComboBox, gbc);

        gbc.gridx = 2;
        gbc.weightx = 0;
        gbc.fill = GridBagConstraints.NONE;
        formPanel.add(browserConfigButton, gbc);

        if (withJavaScriptDebuggerCheckBox != null) {
            gbc.gridx = 3;
            gbc.weightx = 0;
            formPanel.add(withJavaScriptDebuggerCheckBox, gbc);
        }

        gbc.gridx = 0; gbc.gridy = 1;
        gbc.insets = JBUI.insets(2, 0, 2, 6);
        formPanel.add(new JBLabel("URL:"), gbc);

        gbc.gridx = 1; gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.insets = JBUI.insets(2, 4, 2, 8);
        formPanel.add(urlField, gbc);

        panel.add(formPanel);
    }

    @Override
    public void loadConfiguration() {
        if (!isInitialized || browserComboBox == null) {
            return;
        }

        try {
            // Remember what to restore: user's explicit choice takes priority,
            // then whatever was previously selected in the combo.
            String toRestore = userSelectedBrowser != null
                    ? userSelectedBrowser
                    : (String) browserComboBox.getSelectedItem();

            isSettingBrowser = true;
            browserComboBox.removeAllItems();
            browserComboBox.addItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);

            // Use IntelliJ's built-in WebBrowserManager to get active configured browsers
            for (WebBrowser browser : WebBrowserManager.getInstance().getActiveBrowsers()) {
                browserComboBox.addItem(browser.getName());
            }

            // Restore selection if still available in the rebuilt list
            if (toRestore != null) {
                browserComboBox.setSelectedItem(toRestore);
                if (!toRestore.equals(browserComboBox.getSelectedItem())) {
                    browserComboBox.setSelectedIndex(0);
                }
            }
            isSettingBrowser = false;

            updateBrowserControls();

        } catch (Exception e) {
            isSettingBrowser = false;
            LOG.error("Error loading browsers", e);
            if (browserComboBox.getItemCount() == 0) {
                browserComboBox.addItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);
            }
        }
    }

    @Override
    public void resetFrom(@NotNull TomcatRunConfiguration configuration) {
        if (!isInitialized) {
            return;
        }

        try {
            afterLaunchCheckBox.setSelected(configuration.isAfterLaunchEnabled());
            if (withJavaScriptDebuggerCheckBox != null) {
                withJavaScriptDebuggerCheckBox.setSelected(configuration.isWithJsDebugger());
            }
            // When the checkbox is absent (JS plugin not installed) the persisted
            // isWithJsDebugger value is left untouched — if the user later installs the
            // plugin their preference is restored.

            // Drive the editor from the raw stored URL, not getBrowserUrl().
            // getBrowserUrl() is already the effective value, so it hides whether the
            // browser URL is truly stored or auto-derived from the current port. If
            // a legacy config persisted an old auto-like localhost URL with a baked-in
            // port, reading the effective value here would keep that stale string
            // visible forever even after HTTP-port writeback updated the config.
            String storedUrl = configuration.getConfigData().getBrowserConfig().getUrl();
            isSettingUrl = true;
            if (isStoredUrlAutoManaged(configuration, storedUrl)) {
                urlField.setText(configuration.autoBrowserUrl());
                urlIsAutoGenerated = true;
            } else {
                urlField.setText(storedUrl);
                urlIsAutoGenerated = false;
            }
            isSettingUrl = false;

            // Restore saved browser selection — this is the user's persisted choice
            isSettingBrowser = true;
            String savedBrowser = configuration.getBrowserName();
            if (savedBrowser != null && !savedBrowser.isEmpty()) {
                browserComboBox.setSelectedItem(savedBrowser);
                userSelectedBrowser = savedBrowser;
            } else {
                browserComboBox.setSelectedItem(TomcatConstants.BROWSER_SYSTEM_DEFAULT);
                userSelectedBrowser = null;
            }
            isSettingBrowser = false;

            updateBrowserControls();

        } catch (Exception e) {
            LOG.error("Error resetting browser configuration", e);
        }
    }

    @Override
    public void applyTo(@NotNull TomcatRunConfiguration configuration) throws ConfigurationException {
        try {
            if (isInitialized && afterLaunchCheckBox != null) {
                configuration.setAfterLaunchEnabled(afterLaunchCheckBox.isSelected());

                if (urlField != null) {
                    configuration.setBrowserUrl(urlField.getText().trim());
                }

                if (browserComboBox != null && browserComboBox.getSelectedItem() != null) {
                    configuration.setBrowserName(browserComboBox.getSelectedItem().toString());
                }

                if (withJavaScriptDebuggerCheckBox != null) {
                    configuration.setWithJsDebugger(withJavaScriptDebuggerCheckBox.isSelected());
                }
            }
        } catch (Exception e) {
            throw new ConfigurationException("Failed to apply browser configuration: " + e.getMessage());
        }
    }

    @Override
    public boolean isConfigurationValid() {
        return true;
    }

    @Override
    public boolean isModified(@NotNull TomcatRunConfiguration config) {
        if (!isInitialized) {
            return false;
        }

        try {
            if (!Objects.equals(afterLaunchCheckBox.isSelected(), config.isAfterLaunchEnabled())) {
                return true;
            }

            String configUrl = isStoredUrlAutoManaged(config, config.getConfigData().getBrowserConfig().getUrl())
                    ? config.autoBrowserUrl()
                    : config.getConfigData().getBrowserConfig().getUrl();
            String currentUrl = urlField != null ? urlField.getText().trim() : "";
            if (!Objects.equals(currentUrl, configUrl.trim())) {
                return true;
            }

            String configBrowser = config.getBrowserName();
            String currentBrowser = getSelectedBrowser();
            if (!Objects.equals(currentBrowser, configBrowser != null ? configBrowser : TomcatConstants.BROWSER_SYSTEM_DEFAULT)) {
                return true;
            }

            if (withJavaScriptDebuggerCheckBox != null &&
                    withJavaScriptDebuggerCheckBox.isSelected() != config.isWithJsDebugger()) {
                return true;
            }

        } catch (Exception e) {
            LOG.warn("Error checking browser configuration modifications", e);
        }

        return false;
    }

    @Override
    @NotNull
    public List<ValidationInfo> validateSettings() {
        return Collections.emptyList();
    }

    private void updateBrowserControls() {
        if (!isInitialized) {
            return;
        }

        try {
            boolean enabled = afterLaunchCheckBox.isSelected();

            browserComboBox.setEnabled(enabled);
            browserConfigButton.setEnabled(enabled);
            if (withJavaScriptDebuggerCheckBox != null) {
                withJavaScriptDebuggerCheckBox.setEnabled(enabled);
            }
            urlField.setEnabled(enabled);
        } catch (Exception e) {
            LOG.error("Error updating browser controls", e);
        }
    }

    private void configureBrowsers() {
        // Open IntelliJ's built-in "Web Browsers and Preview" settings page
        ShowSettingsUtil.getInstance().showSettingsDialog(project, "Web Browsers and Preview");
        // Reload browser list after settings dialog closes (user may have changed browsers)
        loadConfiguration();
    }

    public boolean isAfterLaunchEnabled() {
        return isInitialized && afterLaunchCheckBox != null && afterLaunchCheckBox.isSelected();
    }

    public String getUrl() {
        return isInitialized && urlField != null ? urlField.getText().trim() : "";
    }

    public String getSelectedBrowser() {
        if (isInitialized && browserComboBox != null && browserComboBox.getSelectedItem() != null) {
            return browserComboBox.getSelectedItem().toString();
        }
        return TomcatConstants.BROWSER_SYSTEM_DEFAULT;
    }

    public boolean isJavaScriptDebuggerEnabled() {
        return isInitialized && withJavaScriptDebuggerCheckBox != null &&
                withJavaScriptDebuggerCheckBox.isSelected();
    }

    /**
     * Updates the port portion of the browser URL when the HTTP port changes.
     * Works for any URL that matches {@code scheme://host:port/path} — so a
     * custom host (e.g. {@code http://127.0.0.1:8080/...}) still gets its
     * port synchronized when the user changes the HTTP port. The host, scheme,
     * and path are preserved; only the numeric port is replaced.
     */
    public void updateUrlPort(String port) {
        if (!isInitialized || urlField == null || port == null || port.isEmpty()) return;

        String currentUrl = urlField.getText();
        String updated = replacePortInUrl(currentUrl, port);
        if (updated != null && !updated.equals(currentUrl)) {
            isSettingUrl = true;
            urlField.setText(updated);
            isSettingUrl = false;
        }
    }

    /**
     * Replaces the numeric port in a {@code scheme://host:port/path} URL with the given port.
     * Returns {@code null} if the URL doesn't match the expected pattern. Package-visible
     * for testing.
     */
    @org.jetbrains.annotations.Nullable
    static String replacePortInUrl(@NotNull String url, @NotNull String port) {
        int schemeEnd = url.indexOf("://");
        if (schemeEnd < 0) return null;
        int hostStart = schemeEnd + 3;
        int portColon = url.indexOf(':', hostStart);
        if (portColon < 0) return null;
        int portEnd = portColon + 1;
        while (portEnd < url.length() && Character.isDigit(url.charAt(portEnd))) {
            portEnd++;
        }
        if (portEnd == portColon + 1) return null; // no digits after colon
        return url.substring(0, portColon + 1) + port + url.substring(portEnd);
    }

    /**
     * Updates the context path portion of the browser URL when deployments change.
     * Only modifies the URL if it was auto-generated — never overwrites a
     * user-customized URL. This is the user's choice to keep.
     */
    public void updateUrlContext(String contextPath) {
        if (!isInitialized || urlField == null || contextPath == null) return;

        // Respect user's custom URL — only update auto-generated ones
        if (!urlIsAutoGenerated) return;

        String currentUrl = urlField.getText();
        if (currentUrl.startsWith(URL_PREFIX)) {
            int portStart = URL_PREFIX.length();
            int pathStart = currentUrl.indexOf('/', portStart);
            String portPart = (pathStart != -1) ? currentUrl.substring(0, pathStart) : currentUrl;
            isSettingUrl = true;
            urlField.setText(portPart + contextPath);
            isSettingUrl = false;
        }
    }

    private static boolean isStoredUrlAutoManaged(@NotNull TomcatRunConfiguration configuration,
                                                  String storedUrl) {
        String normalized = storedUrl == null ? "" : storedUrl.trim();
        if (normalized.isEmpty()) {
            return true;
        }
        if (normalized.equals(configuration.autoBrowserUrl())) {
            return true;
        }
        return looksLikeLegacyAutoUrl(normalized, configuration.getContextPath());
    }

    /**
     * Legacy migration helper: before the single-source-of-truth change, the editor
     * could persist the auto-generated localhost URL with a baked-in port. If that
     * exact localhost/context shape is seen later, treat it as "auto" so the field
     * renders from the current HTTP port instead of freezing the old one.
     */
    static boolean looksLikeLegacyAutoUrl(@NotNull String url, String contextPath) {
        try {
            URI uri = URI.create(url.trim());
            if (!"http".equalsIgnoreCase(uri.getScheme())) {
                return false;
            }
            if (!TomcatConstants.DEFAULT_HOST.equalsIgnoreCase(uri.getHost())) {
                return false;
            }
            if (uri.getPort() <= 0 || uri.getQuery() != null || uri.getFragment() != null) {
                return false;
            }
            String expectedContext = (contextPath == null || contextPath.isEmpty())
                    ? TomcatConstants.DEFAULT_CONTEXT_PATH
                    : contextPath;
            String actualPath = (uri.getPath() == null || uri.getPath().isEmpty())
                    ? TomcatConstants.DEFAULT_CONTEXT_PATH
                    : uri.getPath();
            return expectedContext.equals(actualPath);
        } catch (IllegalArgumentException e) {
            return false;
        }
    }

    private static class BrowserComboRenderer extends com.intellij.ui.SimpleListCellRenderer<String> {
        @Override
        public void customize(@NotNull JList<? extends String> list, String value, int index,
                              boolean selected, boolean hasFocus) {
            if (value != null) {
                setText(value);
                Icon icon = findBrowserIcon(value);
                setIcon(icon != null ? icon : AllIcons.General.Web);
            }
        }

        private Icon findBrowserIcon(String browserName) {
            if (TomcatConstants.BROWSER_SYSTEM_DEFAULT.equalsIgnoreCase(browserName)
                    || "Default".equalsIgnoreCase(browserName)) {
                return AllIcons.General.Web;
            }
            for (WebBrowser browser : WebBrowserManager.getInstance().getBrowsers()) {
                if (browserName.equals(browser.getName())) {
                    return browser.getIcon();
                }
            }
            return null;
        }
    }

    private static boolean isJavaScriptPluginAvailable() {
        try {
            return com.intellij.ide.plugins.PluginManagerCore.getPlugin(
                    com.intellij.openapi.extensions.PluginId.getId("JavaScript")) != null;
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public void dispose() {
        if (urlField != null && urlDocListener != null) {
            urlField.getDocument().removeDocumentListener(urlDocListener);
            urlDocListener = null;
        }
        if (browserComboBox != null && browserActionListener != null) {
            browserComboBox.removeActionListener(browserActionListener);
            browserActionListener = null;
        }
        isInitialized = false;
    }
}
