# JVM Configuration
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Duser.language=en -Duser.country=US

# Plugin Metadata
pluginName=DevTomcat
pluginGroup=com.dev.idea.plugins.tomcat
pluginVersion=1.0.4

# IntelliJ Platform Compatibility
pluginSinceBuild=241.14494.240
pluginUntilBuild=253.*

# Build Platform
platformType=IC
platformVersion=2024.1.5

# JDK Configuration
jdkVersion=17
compatibleJdkVersion=17

# Gradle
gradleVersion=8.13

# Plugin Dependencies
platformPlugins=com.intellij.java

# Kotlin
kotlin.stdlib.default.dependency=false